[project]
name = "p2p-penalty"
authors = ["p2p-penalty-team"]
description = "A decentralized penalty and dispute resolution system on Stacks"
telemetry = false
requirements = []

[contracts.p2p-penalty-contract]
path = "contracts/p2p-penalty-contract.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
